# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy




### 2. Print the NUMPY version and the configuration.


In [5]:
print("numpy version:", numpy.__version__)
show_config = numpy.show_config()


numpy version: 2.0.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/envs/ironhack/include
    lib directory: /opt/anaconda3/envs/ironhack/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/envs/ironhack/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/envs/ironhack/include
    lib directory: /opt/anaconda3/envs/ironhack/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/envs/ironhack/lib/pkgconfig
    version: 0.3.21
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
a = numpy.array([1, 2, 3])



### 4. Print a.


In [7]:
a


array([1, 2, 3])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [9]:
b = numpy.ones((5, 2, 3))



### 6. Print b.


In [10]:
b


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [12]:
print(a.size == b.size)
print("a.size:", a.size)
print("b.size:", b.size)


False
a.size: 3
b.size: 30



### 8. Are you able to add a and b? Why or why not?


In [15]:
try:
    c = a + b
except ValueError as e:
    print("ValueError:", e)
print("a.shape:", a.shape)
print("b.shape:", b.shape)


a.shape: (3,)
b.shape: (5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [16]:
c = b.transpose(1,2,0)
print(c.shape)

(2, 3, 5)


In [21]:
import numpy as np
a = np.random.random((2, 3, 5))
print(a.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [22]:
d = a + c
print(d)


[[[1.47903122 1.46916022 1.24571351 1.71308284 1.02798356]
  [1.92480683 1.62992284 1.70770396 1.28792097 1.85234743]
  [1.76147203 1.99865335 1.36892343 1.87155288 1.49277359]]

 [[1.60325948 1.88559084 1.00660443 1.87480167 1.41025937]
  [1.84438982 1.79503835 1.66840715 1.21081536 1.17144292]
  [1.35120528 1.74745681 1.67394459 1.41472778 1.78037667]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [26]:
print(a)
print(d)
#because a is filled with random numbers between 0 and 1
#and array c is filled with ones
#when we added array a and c together each element in array a is increased by 1


[[[0.47903122 0.46916022 0.24571351 0.71308284 0.02798356]
  [0.92480683 0.62992284 0.70770396 0.28792097 0.85234743]
  [0.76147203 0.99865335 0.36892343 0.87155288 0.49277359]]

 [[0.60325948 0.88559084 0.00660443 0.87480167 0.41025937]
  [0.84438982 0.79503835 0.66840715 0.21081536 0.17144292]
  [0.35120528 0.74745681 0.67394459 0.41472778 0.78037667]]]
[[[1.47903122 1.46916022 1.24571351 1.71308284 1.02798356]
  [1.92480683 1.62992284 1.70770396 1.28792097 1.85234743]
  [1.76147203 1.99865335 1.36892343 1.87155288 1.49277359]]

 [[1.60325948 1.88559084 1.00660443 1.87480167 1.41025937]
  [1.84438982 1.79503835 1.66840715 1.21081536 1.17144292]
  [1.35120528 1.74745681 1.67394459 1.41472778 1.78037667]]]



### 12. Multiply a and c. Assign the result to e.


In [27]:
e = a*c




### 13. Does e equal to a? Why or why not?


In [28]:
print(np.array_equal(e, a))



True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [29]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [30]:
f = np.empty((2, 3, 5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [31]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_max:
                f[i, j, k] = 100
            elif value == d_min:
                f[i, j, k] = 0
            elif value > d_min and value < d_mean:
                f[i, j, k] = 25
            elif value > d_mean and value < d_max:
                f[i, j, k] = 75
            else:
                f[i, j, k] = 50






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [32]:
print(d)
print(f)


[[[1.47903122 1.46916022 1.24571351 1.71308284 1.02798356]
  [1.92480683 1.62992284 1.70770396 1.28792097 1.85234743]
  [1.76147203 1.99865335 1.36892343 1.87155288 1.49277359]]

 [[1.60325948 1.88559084 1.00660443 1.87480167 1.41025937]
  [1.84438982 1.79503835 1.66840715 1.21081536 1.17144292]
  [1.35120528 1.74745681 1.67394459 1.41472778 1.78037667]]]
[[[ 25.  25.  25.  75.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 75. 100.  25.  75.  25.]]

 [[ 75.  75.   0.  75.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [34]:
f_string = np.empty(f.shape, dtype=str)
for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            if f[i, j, k] == 0:
                f_string[i, j, k] = "A"
            elif f[i, j, k] == 25:
                f_string[i, j, k] = "B"
            elif f[i, j, k] == 50:
                f_string[i, j, k] = "C"
            elif f[i, j, k] == 75:
                f_string[i, j, k] = "D"
            elif f[i, j, k] == 100:
                f_string[i, j, k] = "E"

print(f_string)

[[['B' 'B' 'B' 'D' 'B']
  ['D' 'D' 'D' 'B' 'D']
  ['D' 'E' 'B' 'D' 'B']]

 [['D' 'D' 'A' 'D' 'B']
  ['D' 'D' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'D']]]
